### ISSUE TITLE
Autodetect dashboard URL with a proxy

### ISSUE THREAD

**Issue by ScottWales** [dask/dask-labextension#109]
Is there a way to get dask-labextension to autodetect a jupyter-server-proxy URL like `proxy/8787` instead of the cluster's dashboard URL?

I'm running Jupterlab on a remote machine, forwarding its port over SSH so I can connect to it.

If I start a cluster within a notebook, and then use the 'Autodetect dashboard URL' button in dask-labextension, it finds an address like `http://127.0.0.1:8787`

This URL doesn't work however, as I've not forwarded port 8787 locally (and in general can't predict which port the cluster will start on, it's a multi-user environment so the cluster might move to a different port), and all of the Dask control buttons stay dark.

If I manually enter a jupyter-server-proxy URL like `proxy/8787` however all of the Dask buttons light up and I can see the worker panels etc.

**Comment by jacobtomlinson** [comment]
Thanks for raising this @ScottWales.

The search button inspects the cluster object you created in order to find the dashboard URL. As the cluster object is local to your notebook in this case it will give you a default URL relative to the notebook, not the location you are port forwarding from.

You can override the [default](https://github.com/dask/distributed/blob/8eadf5e8fa56673aef9063fa91c52f4715638b6d/distributed/distributed.yaml#L119) (which is `"{scheme}://{host}:{port}/status"`) in your Dask config with the correct URL scheme for your setup. So for the example you gave above it would be

```yaml
# ~/.config/dask/distributed.yaml

distributed:
 dashboard:
    link: "proxy/{port}/status"
```

Or you can set this by environment variable also before running Jupyter Lab.

```bash
export DASK_DISTRIBUTED__DASHBOARD__LINK="proxy/{port}/status"
```

**Comment by ScottWales** [comment]
Works perfectly, thanks @jacobtomlinson
