### ISSUE TITLE
List of routes no longer being detected?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#137]
When I do a clean install of JupyterLab and dask-labextension, I no longer get an up-to-date list of all of the plots that are avaialble.

```
conda create -c conda-forge -n fresh jupyterlab nodejs dask-labextension dask
conda activate fresh
jupyter labextension install dask-labextension
jupyter serverextension enable dask_labextension
jupyter lab
```

```python
from dask.distributed import Client
client = Client()
```

"Cluster Map" does not occur on the sidebar

cc @jacobtomlinson perhaps?

**Comment by ian-r-rose** [comment]
There are two cases we have historically tried to cover here:
1. The case where a user creates a client in a notebook, and then connects to the dashboard manually (by, e.g., entering `http://localhost:8787`, and 
2. The case where the cluster client is managed by the extension itself, and proxies the dashboard endpoints under the Jupyter server.

As far as I know, checking for the available dashboard routes (using the `individual-plots.json` endpoint) has never worked in case (1). This was, at least at the time, due to the CORS policies set on the bokeh server. The workaround has been this hack: https://github.com/dask/dask-labextension/blob/33a4b9db19a5591e8f6fbdc22ef49dda8cbc7c03/src/dashboard.tsx#L604-L626
The last time we visited this, nobody was successful in configuring the bokeh server to accept CORS requests from the Jupyter server, but I would love to revisit that and remove the svg hack.

**Comment by ian-r-rose** [comment]
Cf. #https://github.com/dask/dask-labextension/pull/96
