### ISSUE TITLE
JS Code Contribution Questions

### ISSUE THREAD

**Issue by brianblocker** [dask/dask-labextension#139]
Hey @mrocklin, I work for @mmccarty and a few members of my team (JS devs) are about to start contributing here. Hopefully we can even help out with some of the issues/features!

We have a particular set of prettier / typescript settings that we use across all of our projects. We also have some patterns that we follow internally. I want to make sure that we aren't stepping on any toes or anything. Are there any "sacred rules" or settings or anything that we should be aware of? What things are people holding near and dear to their hearts that we shouldn't try to modify, lest we invoke the wrath of Khan? Would love to get an idea of any of that so we can collaborate in the most friendly way possible 😄

**Comment by mrocklin** [comment]
Hi @brianblocker ! 

I'm glad to hear that you all are willing to pitch in.  I'm probably not the person to ask here, but @ian-r-rose and @jacobtomlinson may have thoughts.  If you have more information about the kinds of systems you're using maybe you could share more about them so that people here can weigh in?

**Comment by brianblocker** [comment]
Sure thing! And Howdy @ian-r-rose & @jacobtomlinson. So we're primarily React devs, we tend to leverage the latest stable version of React in our projects (and keep dependencies updated accordingly), we love UI tests, we leverage the last stable versions of Typescript usually as well, and I believe for formatting we're moving towards https://standardjs.com/. We also tend to favor smaller, specific-purpose files over larger, more robust files.

Would love thoughts/feedback/input!

**Comment by jacobtomlinson** [comment]
Great to see you here @brianblocker!

Things are less mature in the JS space here. We have conventions around Python in terms of `flake8`, `black`, `pytest`, etc, but no equivalent for JS. I guess because JS can be far more up to interpretation and we have a limited number of folks contributing here.

As this is an extension for Jupyter Lab I expect we would just default to [their contributing guide](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html) in an attempt for some kind of consistency with the rest of the community. They seem to just advise prettier on default settings and running tests with `jlpm` (an opinionated `yarn` wrapper specifically for Jupyter Lab). For things like dependency versions we should probably support the minimum version that Jupyter Lab does.

I'm sure we would all support increasing maturity here and would be happy to defer to JS devs like yourselves on best practices (many of us are primarily Python devs). I would absolutely support using something like StandardJS and adding it to CI to enforce it, the same way we do with `black`.

For file structure, I'm also a big fan of smaller, specific-purpose files. As a community we also have a policy of avoiding [indirection](https://matthewrocklin.com/blog/work/2019/06/23/avoid-indirection) where possible, so this can be a balancing act but generally means things end up being well scoped and easy for novice users to parse.

I think a good way to summarise our preferences would be "maintainability, readability and testability" are key. We also embrace the fact that our community is primarily Python, so we may end up naming things or structuring things in a way which will be more familiar to a Python dev than a JS dev. I would hope any Python dev could look at our JS code, build it, test it and fix things without too much pain or learning curve.

**Comment by brianblocker** [comment]
This sounds _wonderful_. We *love* `prettier` and it's totally possible to have it follow `standardjs` so that we can just get the benefit on save, or in CI, etc. And I'd love some help to make sure how we're naming things and structuring things lines up with what Python devs would expect.

Looking forward to collaborating here! Going to close out this issue and open up a few new ones addressing:

- Implementing `standardjs` (updating `prettier` config to make sure it's leveraging this) - this will be potentially a "massive line change" PR due to things like `standardjs` removing semicolons. Beyond code styling changes, that PR won't have any other modifications
- Increasing test coverage for the existing JS codebase - This would need to happen prior to making any changes to file structure / organization so we can be confident those changes wouldn't be breaking!
- Reorganization of the JS codebase - Logical, agreed upon changes that result in increased maintainability, readability, and testability (while also avoiding indirection)

Happy to discuss further if anyone would like, otherwise I intend to get started on creating these issues soon!

**Comment by jacobtomlinson** [comment]
Sounds great @brianblocker

**Comment by jacobtomlinson** [comment]
Whoops accidental reopen

**Comment by ian-r-rose** [comment]
Thanks for the introduction @brianblocker, we welcome some help on the JS side, especially around UI testing! Historically, one of the most challenging things to test in this project has also been covering the many ways that people want to connect to dask clusters, so some end-to-end testing of that would be very valuable.

I am also a big fan of prettier and ts linting. If you have specific rules that you want to discuss, I'd love to hear about them. My main request is that, since this package is part of the broader JupyterLab ecosystem, it would be nice to keep the linting rules *mostly* compatible with those used in [JupyterLab](https://github.com/jupyterlab/jupyterlab/) itself.
