### ISSUE TITLE
hiding/restoring tabs in jupyterlab

### ISSUE THREAD

**Issue by SultanOrazbayev** [dask/dask-labextension#184]
Currently, if I open some dask tabs in jupyterlab, they will become a fixed part of the layout, so if I switch to a notebook/workflow that doesn't involve dask, they take up screen space. 

If I close dask tabs, then later I would need to reopen the dask tabs manually, so it would be great if there was a button (similar to the cell properties button on the screenshot) that could hide/unhide dask tabs (preserving layout).
 
![image](https://user-images.githubusercontent.com/1610850/115565119-02834300-a2b1-11eb-8d0e-ad7656cb185f.png)

**Comment by jacobtomlinson** [comment]
I'm not sure if this is something we can do from the extension.

**Comment by SultanOrazbayev** [comment]
Ah, ok, thanks!

**Comment by mrocklin** [comment]
I think that a possible broader question is "Can JupyterLab support
pre-configured layouts?"

I recommend waiting until California wakes up and @ian-r-rose has a chance
to comment

**Comment by ian-r-rose** [comment]
@SultanOrazbayev good question! I think there are two related questions here:
1. Can JupyterLab have pre-configured layouts? The answer is yes, but it's not particularly ergonomic or easy to use (the primary intention for it is to preserve layout upon page refresh, but we can use it to also distribute layouts).
2. Can we hide/restore a complex layout of dask dashboard panels? I think this is more what you are after. You might be interested to try the "Simple" layout toggle, in the lower left corner (since JupyterLab 3). This will show only the currently active document (e.g., a notebook). Once you toggle it off, it will restore the old layout, which might include dask plots.
![image](https://user-images.githubusercontent.com/5728311/115575606-93d5c380-a277-11eb-9aa5-a665274329f7.png)

**Comment by SultanOrazbayev** [comment]
@ian-r-rose Thank you for the quick feedback! I think this was a bit rushed of me to submit this feature suggestion, since a lot of it is specific to my setup (I'm using a wide-screen, and have a couple of notebooks/config files in parallel).
