### ISSUE TITLE
JLab 4-compatible release

### ISSUE THREAD

**Issue by ian-r-rose** [dask/dask-labextension#269]
With #263 in I'd like to get a release out today or tomorrow. Any objections @jrbourbeau or @jacobtomlinson?

**Comment by jrbourbeau** [comment]
👍

**Comment by ian-r-rose** [comment]
This is done, thanks again to @mahendrapaipuri for the work!

**Comment by jrbourbeau** [comment]
Woo! Thanks @mahendrapaipuri @ian-r-rose

**Comment by krassowski** [comment]
Hi all thank you for the update! This is rather inconsequential but I noted that while there is a tag for 7.0 (https://github.com/dask/dask-labextension/releases/tag/7.0.0) there is no GitHub release so it does not show up on the front page of the repository. Not a biggie but would help especially since there is no PyPI badge in the readme.

**Comment by jacobtomlinson** [comment]
@krassowski I've made the missing release. Thanks for the nudge
